export const SliderData = [
  {
    id: "slide1",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 1 Image",
    title: "Liewood",
    text: "Liewood is based in Copenhagen and our universe is deeply rooted in the Nordic design tradition. They advocate slow living, creating irresistible products for the modern family that will last for generations. Liewood products are created on the basis of original workmanship, the finest materials and with a modern approach to design.",
    action: "Slide 1 Image Action",
    actionHref: "href",
  },
  {
    id: "slide2",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 2 Image",
    title: "Konges Sløjd",
    text: "Konges Sløjd is a creative brand that salutes the wild, varied and perfectly imperfect life with children. The brand aims to blaze a trail for garments, toys and interiors produced in a way that is kinder to the environment and made to last. Everything is crafted to survive snuggly newborns, adventurous toddlers or curious children and still be passed on. They embrace the ups and downs of parenthood and hope to bring a little bit of simplicity into your lives through their comfy, technical and versatile collections.",
    action: "Slide 2 Image Action",
    actionHref: "href",
  },
  {
    id: "slide3",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 3 Image",
    title: "Soft Gallery",
    text: "Every season, Soft Gallery collaborates with both local and international artists. They convert unique seasonal themes into prints and hand embroideries, bringing life to the soft canvas and giving each collection an organic flow with new beautiful impulses and variations. The clothes are luxurious and contemporary with an added artistic twist. Soft Gallery places great emphasis on high-quality materials and comfortable silhouettes. The designs are honest, timeless and personal.",
    action: "Slide 3 Image Action",
    actionHref: "href",
  },
  {
    id: "slide4",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 3 Image",
    title: "CamCam Copenhagen",
    text: "Cam Cam Copenhagen’s core originates from the love of babies and children, and a belief that they only deserve the best. They create quality, timeless and tactile design for children, offering poetic products which help create calm and harmonious environments.Their overall design focus is sustainability - this means sustainable, organic production and enduring design and material quality.",
    action: "Slide 3 Image Action",
    actionHref: "href",
  },
  {
    id: "slide5",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 3 Image",
    title: "Smallstuff",
    text: "At Smallstuff they love colors and beautiful designs with a unique mix and match opportunity. In all designs they use natural materials; cotton, wool and wood, combined with handcrafted crochet and knitted items. They want to inspire children and their creativity by entering their universe in a happy and childlike way, while appealing to parents with high quality, natural products.",
    action: "Slide 3 Image Action",
    actionHref: "href",
  },
  {
    id: "slide6",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 3 Image",
    title: "Wauw Kapow",
    text: "Wauw Kapow creates children’s clothes inspired by the playful spirit of children.They  believe children are free to wear whatever they want, and a lot of our clothes are therefore not gender-specific. To resist the hard job of being worn by playing children all day,  our clothes are made of high-quality textiles. Their designs are inspired by modern and conceptional arts and colors, different animal shapes and textures and the comfortable and functional elements of streetwear.",
    action: "Slide 3 Image Action",
    actionHref: "href",
  },
  {
    id: "slide7",
    imagePath: "/assets/img05.png",
    imageAlt: "Slide 3 Image",
    title: "Fabelab",
    text: "Fabelab is a playful organic Scandinavian children’s interior brand, founded in Copenhagen, that believes in creating high-quality, innovative, and responsibly made products. Their selection of wooden toys is easy on the eyes, consciously crafted, and most importantly fun for the little ones to play with. All their wooden toys are FSC® certified, which ensures that the wood comes from responsibly managed forests that provide environmental, social, and economic benefits.",
    action: "Slide 3 Image Action",
    actionHref: "href",
  },
];
